"""Central configuration. Every knob and every path lives here (spec 3)."""

from __future__ import annotations

import os
import sys
from pathlib import Path
from typing import Any

# --- roots -------------------------------------------------------------
# WORK_ROOT is the (interruptible) working directory. PERSISTENT_ROOT is the
# durable location for anything that must survive a lost session: manifests,
# checkpoints, results. Override either with an environment variable.
WORK_ROOT = Path(os.environ.get("OCR_WORK_ROOT", Path(__file__).resolve().parent.parent))
PERSISTENT_ROOT = Path(
    os.environ.get("OCR_PERSISTENT_ROOT", WORK_ROOT.parent / "OCR_Model_Training_output")
)

PATHS: dict[str, Path] = {
    "work_root": WORK_ROOT,
    "persistent_root": PERSISTENT_ROOT,
    # inputs (read-only, local)
    "raw_dir": WORK_ROOT / "data" / "raw" / "devanagari",
    # regenerable bulk data, kept on fast local disk (spec 2, Drive I/O warning)
    "lines_dir": WORK_ROOT / "data" / "lines",
    # durable outputs
    "manifests_dir": PERSISTENT_ROOT / "manifests",
    "checkpoints_dir": PERSISTENT_ROOT / "checkpoints",
    "results_dir": PERSISTENT_ROOT / "results",
    # human inspection artefacts
    "inspect_dir": WORK_ROOT / "inspect",
}

CONFIG: dict[str, Any] = {
    # --- experiment identity ---
    "run_name": None,  # auto-generated by build_run_name()
    "seed": 42,
    # --- data ---
    "dataset": "devanagari",  # devanagari | malayalam | bengali
    "data_fraction": 1.0,  # THE SCALING-LAW AXIS. 0.125, 0.25, 0.5, 1.0
    "max_train_lines": None,  # absolute cap, alternative to fraction
    "val_split": 0.10,
    "test_split": 0.10,
    # --- label noise ---
    "noise_type": "none",  # none | char_flip | line_swap
    "noise_rate": 0.0,  # THE NOISE AXIS. 0.0, 0.1, 0.2, 0.4
    "noise_seed": 1234,  # SEPARATE from training seed, see spec 8.3
    # --- image preprocessing ---
    "img_height": 32,
    "img_max_width": 512,
    "grayscale": True,
    "strip_zero_width_joiners": True,  # spec 7.1 step 3; decision logged
    # --- model ---
    "cnn_width_mult": 1.0,  # MODEL-SIZE AXIS for later runs
    "rnn_hidden": 256,
    "rnn_layers": 2,
    "dropout": 0.1,
    # --- training ---
    "batch_size": 32,
    "epochs": 60,
    "lr": 3e-4,
    "optimizer": "adam",
    "weight_decay": 0.0,
    "scheduler": "cosine",
    "grad_clip": 5.0,
    "early_stop_patience": 12,
    "augment": False,  # keep False for scaling runs
    # --- runtime ---
    "num_workers": 4,
    "device": "cuda",
}


def build_run_name(cfg: dict[str, Any]) -> str:
    """Encode dataset, data_fraction, noise_type, noise_rate and seed (spec 3)."""
    return (
        f"{cfg['dataset']}"
        f"_d{int(round(cfg['data_fraction'] * 100)):03d}"
        f"_{cfg['noise_type']}{int(round(cfg['noise_rate'] * 100)):02d}"
        f"_s{cfg['seed']}"
    )


def make_dirs() -> None:
    """Create every configured output directory."""
    for key in ("lines_dir", "manifests_dir", "checkpoints_dir", "results_dir", "inspect_dir"):
        PATHS[key].mkdir(parents=True, exist_ok=True)


def use_utf8_stdout() -> None:
    """Devanagari output must not die on a cp1252 console."""
    for stream in (sys.stdout, sys.stderr):
        if hasattr(stream, "reconfigure"):
            stream.reconfigure(encoding="utf-8", errors="replace")


def describe_device() -> str:
    """Report CUDA availability and the device name (spec 2)."""
    import torch

    lines = [
        f"torch {torch.__version__}",
        f"torch.version.cuda: {torch.version.cuda}",
        f"torch.cuda.is_available(): {torch.cuda.is_available()}",
    ]
    if torch.cuda.is_available():
        lines.append(f"device count: {torch.cuda.device_count()}")
        lines.append(f"device name: {torch.cuda.get_device_name(0)}")
    else:
        lines.append("device name: <none - no CUDA device visible>")
    return "\n".join(lines)


def require_cuda() -> "object":
    """Abort with a clear message if CPU only (spec 2)."""
    import torch

    if not torch.cuda.is_available():
        raise RuntimeError(
            "No CUDA device visible. This pipeline is specified to train on GPU; "
            "refusing to fall back to CPU. "
            f"torch={torch.__version__}, torch.version.cuda={torch.version.cuda}"
        )
    return torch.device("cuda")
